### ISSUE TITLE
Remove Trackers

### ISSUE THREAD

**Issue by jerome-jutteau** [Horizontal-org/Tella-Android#173]
Hi,

 In [Exodus tracker report for 2.0.11 version](https://reports.exodus-privacy.eu.org/en/reports/297172/), it seems Tella contains some trackers:
- [Google CrashLytics](https://reports.exodus-privacy.eu.org/en/trackers/27/)
- [Google Firebase Analytics](https://reports.exodus-privacy.eu.org/en/trackers/49/)

## What is changing? 

Please, remove those trackers or at least explicitly mention those in documentation.

Information could include:
- tracking technology
- hosting service
- which data is sent
- for which purpose
- who can access this data

## How will this impact users?

As Tella claim to manipulate sensible data, having trackers without any information on those in main README.md could be a major trust issue.

**Comment by carohadad** [comment]
hello @jerome-jutteau ! I'm sorry we didn't answer your issue before. We have been working on your request over the last few months.

First of all, we have a new [documentation platform](https://docs.tella-app.org/) that includes user guides, videos, tutorial and details about the app features. On the documentation we added a [Privacy and Security section](https://docs.tella-app.org/security-and-privacy) where we explain what data we collect. We also linked our [privacy policy](https://docs.tella-app.org/privacy-policy) that contains a lot details about how data is  collected and managed.
>  we only collect the minimum amount of data that is necessary to fulfill the purpose of Tella. We never collect personally identifiable information. We never disclose, share, or sell any of your data to third parties.

About trackers, as you mentioned, the Tella version that's available on the PlayStore currently includes two trackers, Google Crashlytics (not Google Analitics) and Google Firebase Analytics, which are used to detect bugs and crashes.

However, we understand that some users may prefer fully trackers-free and Google-free version of the app. That's why we're excited to share that such a version is currently available for download from the [F-droid store](https://f-droid.org/packages/org.hzontal.tellaFOSS/). 

On the documentation platform that I mentioned above we included information about Tella-FOSS and you can find it's code repository here: https://github.com/Horizontal-org/Tella-Android-FOSS.

We will update this README soon, with the details about Tella-FOSS, but it currenly already includes the privacy policy and the link to the documentation.

Thank you for your suggestion and we hope Tella-FOSS is useful for you. Please, if you have any questions or comments do not hesitate to [contact us](https://docs.tella-app.org/contact-us)
