### ISSUE TITLE
Make it possible to trust Tella by removing Google Trackers

### ISSUE THREAD

**Issue by neonota** [Horizontal-org/Tella-Android#210]
Currently tella uses Google Analytics and Tag Manager which eliminates the purpose of using this app for anything. 
![SmartSelect_20230501-100340_Warden](https://user-images.githubusercontent.com/114842102/235405223-62a67ba0-6c9f-4cf2-acc0-b026b12b31ca.jpg)

...

![SmartSelect_20230501-100330_Warden](https://user-images.githubusercontent.com/114842102/235405237-61dad3a8-00fc-4fa8-84d1-3a28b4c91259.jpg)

Kindly remove these as soon as possible.

**Comment by neonota** [comment]
Otherwise we have to believe this is a project led by NSA or Mossad.

**Comment by carohadad** [comment]
Thank you @neonota  for your question regarding Tella Android and its use of trackers. We appreciate your interest in our app and the measures we take to ensure the security for at-risk users.

As you mentioned, Tella Android currently includes two trackers, Google Crashlytics (not Google Analitics) and Google Firebase Analytics, which are used to detect bugs and crashes. Please note that users can opt-out of Google Crashlytics by going to Settings > General and toggling off “Bug reports”. However, we understand that some users may prefer fully trackers-free and Google-free version of the app. That's why we're excited to share that such a version is currently under development and will soon be available for download from the F-droid store.  We have been working on this version for some months, and we estimate that we will be able to release this version in the next few weeks. You can follow the discussion around getting Tella on F-Droid here: https://gitlab.com/fdroid/rfp/-/issues/2346. 

Regarding the logging interceptor and timber loggers: these are used to improve the readability of logs for Tella developers when we test the app internally. We only used Logging Interceptor for debugging, it wasn't ant production builds for users, [as you can see here](https://github.com/Horizontal-org/Tella-Android/blob/e8ad9525b2a00836090bdc62af66ac4dfc2a5f22/mobile/src/main/java/rs/readahead/washington/mobile/data/uwazi/UwaziService.java#LL126C37-L126C37). So, only the info from our own debug builds on testing devices were logged.

We use the Timber library just to make logging easier and more readable. It is not used to share the logs. That being said, because of your question, we realized we are not using the Logging Interceptor anymore, so we will be removing it on the next release: https://github.com/Horizontal-org/Tella-Android/commit/a784a4566f6465d0d7495b17cb3a0a0d8a99ae49


In case you want to learn more about Tella privacy and security details, you can read our docs: https://docs.tella-app.org/security-and-privacy and our privacy policy: https://docs.tella-app.org/privacy-policy

And last, but not least, you can access our latest security audit here: https://drive.google.com/file/d/11mPB2KZLHb6blmNuk_qyXYcn4BSVYNFT/view. We will be incorporating it soon to the [Security Audit](https://docs.tella-app.org/security-and-privacy#security-audits) section of our documentation.

Once again, thank you for your feedback and interest in Tella Android. We're committed to providing a secure and reliable app that meets the needs of all our users. If you have any further questions or concerns, please don't hesitate to let us know.

**Comment by carohadad** [comment]
Hello again @neonota . Our Tella-FOSS version has been published on the f-droid store: https://f-droid.org/packages/org.hzontal.tellaFOSS/

Please feel free to test it, review the documentation and share with us here or in the [Tella-FOSS repo](https://github.com/Horizontal-org/Tella-Android-FOSS) any feedback you might have.

- [Documentation](https://docs.tella-app.org/open-source)
- [Available features](https://docs.tella-app.org/features)
- [Release notes] (https://docs.tella-app.org/releases#tella-foss-2015-based-on-android-2015---july-10-2023)

Closing for now. Please re-open if we are missing something.
